In [1]:
import numpy as np 

In [5]:
a = [3,4,5,6.0]
type(a)

list

In [7]:
np.array(a)

array([3., 4., 5., 6.])

In [20]:
v = np.array([[1,2,3], [3,4]])

In [21]:
v

array([list([1, 2, 3]), list([3, 4])], dtype=object)

In [12]:
v[0][0]

1

In [13]:
v.shape

(2, 3)

In [18]:
np.array([4,5,6,7],ndmin= 20)


array([[[[[[[[[[[[[[[[[[[[4, 5, 6, 7]]]]]]]]]]]]]]]]]]]])

In [19]:
np.array([4,5,6,7] , dtype = complex)

array([4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [27]:
np.array([(3,4) , (5,6)])

array([[3, 4],
       [5, 6]])

In [34]:
n = np.array([(3,4) , (5,6)],dtype = [('a' , '<i4'),('b' , '<i2')])

In [35]:
type(n[0][0])

numpy.int32

In [36]:
type(n[0][1])

numpy.int16

In [41]:
m = np.mat([1,2,3,4])
m

matrix([[1, 2, 3, 4]])

In [39]:
np.array([5,6,7,7])

array([5, 6, 7, 7])

In [42]:
np.array(m)

array([[1, 2, 3, 4]])

In [43]:
np.asanyarray([5,6,7,78])

array([ 5,  6,  7, 78])

In [44]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [ ]:
np.asanyarray()

In [45]:
a = np.array([4,5,6,7,8])

In [46]:
b = a 

In [47]:
b 

array([4, 5, 6, 7, 8])

In [49]:
b[0] = 535

In [50]:
b

array([535,   5,   6,   7,   8])

In [51]:
a 

array([535,   5,   6,   7,   8])

In [52]:
c = np.copy(a)

In [53]:
c 

array([535,   5,   6,   7,   8])

In [54]:
a

array([535,   5,   6,   7,   8])

In [56]:
c[0] = 343

In [57]:
c

array([343,   5,   6,   7,   8])

In [58]:
a

array([535,   5,   6,   7,   8])

In [59]:
a[0] = 435354345
a

array([435354345,         5,         6,         7,         8])

In [60]:
c

array([343,   5,   6,   7,   8])

In [61]:
np.fromfunction(lambda x,y : x==y , (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [64]:
np.fromfunction(lambda x,y : x - y*6 , (3,4))

array([[  0.,  -6., -12., -18.],
       [  1.,  -5., -11., -17.],
       [  2.,  -4., -10., -16.]])

In [73]:
np.fromstring('6,7', dtype = int ,sep= ',')

array([6, 7])

In [74]:
a = [[3,4,5] ,[6,7,8] ,[6,7,9]]

In [83]:
n = np.array(a)

In [84]:
n

array([[3, 4, 5],
       [6, 7, 8],
       [6, 7, 9]])

In [85]:
n.ndim

2

In [86]:
n.size

9

In [87]:
n.shape


(3, 3)

In [93]:
n.dtype


dtype('int32')

In [91]:
m = np.array([])

In [92]:
m.ndim

1

In [96]:
range(7.,5.,.0)

TypeError: 'float' object cannot be interpreted as an integer

In [100]:
 n = np.arange(2.5 ,9.87 , .5)

In [101]:
list(n)

[2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5]

In [117]:
np.linspace(3,7.9, axis = 0 )

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9])

In [121]:
np.zeros((2,5,6,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0.,

In [125]:
np.ones((2,3,4)) +1

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [133]:
np.empty((2,4))

array([[5.17780797e-321, 1.09707182e-311, 4.68374232e-321,
        1.09707182e-311],
       [4.18967668e-321, 1.09707182e-311, 4.96041908e-321,
        1.09707182e-311]])

In [134]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [136]:
np.logspace(5.6 , 7.8 ,6 ,base=2)

array([ 48.50293013,  65.79928491,  89.26359465, 121.09537878,
       164.27851489, 222.8609442 ])

In [142]:
m = np.random.rand(4,5)

In [143]:
m

array([[0.27944988, 0.09975932, 0.1862148 , 0.19371134, 0.80493664],
       [0.20407041, 0.58841091, 0.96239333, 0.7072468 , 0.46104563],
       [0.69639219, 0.19890337, 0.6799465 , 0.29131176, 0.6545221 ],
       [0.06130352, 0.20464819, 0.51256711, 0.31294594, 0.30997545]])

In [146]:
m.reshape(5,4)

array([[0.27944988, 0.09975932, 0.1862148 , 0.19371134],
       [0.80493664, 0.20407041, 0.58841091, 0.96239333],
       [0.7072468 , 0.46104563, 0.69639219, 0.19890337],
       [0.6799465 , 0.29131176, 0.6545221 , 0.06130352],
       [0.20464819, 0.51256711, 0.31294594, 0.30997545]])

In [151]:
m.reshape(3,10)

ValueError: cannot reshape array of size 20 into shape (3,10)

In [152]:
np.random.randn(5,6)

array([[-0.22233709,  0.53452036, -1.00488276,  0.06114795, -0.87510193,
         0.81289548],
       [ 1.57144402,  0.01910833, -1.41600346,  1.3891972 , -0.47906297,
         0.49389232],
       [ 0.13791981, -1.79302464,  0.15846341,  0.10820797,  1.16216907,
         1.10989971],
       [ 0.99057913,  0.59838955,  0.44981658, -0.63946927, -0.85314034,
         0.3574283 ],
       [-0.61203974,  0.74364044,  0.30219256,  1.52127543, -0.80302858,
        -0.51497881]])

In [155]:
a = np.random.randint(3,8 , (5,6))

In [156]:
a

array([[4, 3, 7, 4, 5, 3],
       [7, 6, 5, 4, 3, 4],
       [3, 3, 7, 5, 7, 5],
       [6, 7, 3, 7, 6, 5],
       [4, 6, 3, 5, 7, 5]])

In [160]:
a[0:2,0:2]

array([[4, 3],
       [7, 6]])

In [162]:
a[a>5]

array([7, 7, 6, 7, 7, 6, 7, 7, 6, 6, 7])

In [163]:
a[0][0]=90

In [164]:
a

array([[90,  3,  7,  4,  5,  3],
       [ 7,  6,  5,  4,  3,  4],
       [ 3,  3,  7,  5,  7,  5],
       [ 6,  7,  3,  7,  6,  5],
       [ 4,  6,  3,  5,  7,  5]])

In [165]:
m = np.array([[3,4,5],[5,6,7]])

In [166]:
m

array([[3, 4, 5],
       [5, 6, 7]])

In [174]:
 n= np.array([[67,4,5],[5,0,5]])

In [175]:
n

array([[67,  4,  5],
       [ 5,  0,  5]])

In [176]:
m+n

array([[70,  8, 10],
       [10,  6, 12]])

In [177]:
m-nm =

array([[-64,   0,   0],
       [  0,   6,   2]])

In [178]:
m*n

array([[201,  16,  25],
       [ 25,   0,  35]])

In [179]:
m1 = np.array([[0,1],[2,3]])

In [180]:
m1

array([[0, 1],
       [2, 3]])

In [181]:
m2 = np.array([[2,3],[1,8]])

In [182]:
m2

array([[2, 3],
       [1, 8]])

In [183]:
m1*m2

array([[ 0,  3],
       [ 2, 24]])

In [184]:
m1@m2

array([[ 1,  8],
       [ 7, 30]])

In [185]:
m1

array([[0, 1],
       [2, 3]])

In [186]:
m1**2

array([[0, 1],
       [4, 9]], dtype=int32)

In [187]:
pow(m1,2)

array([[0, 1],
       [4, 9]], dtype=int32)

In [273]:
m = np.zeros((3,4)).reshape((1,2,-1))

In [275]:
np.linspace(3,7,.45)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  """Entry point for launching an IPython kernel.


array([], dtype=float64)

In [255]:
m+2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [256]:
n1  = np.array([1,3,4,2])

In [257]:
n1

array([1, 3, 4, 2])

In [258]:
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [259]:
m+n1

array([[1., 3., 4., 2.],
       [1., 3., 4., 2.],
       [1., 3., 4., 2.]])

In [267]:
n2 = np.array([[3,4,5]])

In [268]:
n2.shape


(1, 3)

In [269]:
n2.ndim

2

In [220]:
m = np.random.rand(4,5).reshape(10,2)

In [221]:
m

array([[0.14455958, 0.20938182],
       [0.83605175, 0.55520719],
       [0.43425885, 0.48619   ],
       [0.39130041, 0.49192625],
       [0.76129507, 0.49570495],
       [0.46454378, 0.68464389],
       [0.60547977, 0.86975051],
       [0.58402069, 0.52695175],
       [0.51751644, 0.21480888],
       [0.78930128, 0.80285651]])

In [222]:
m1 = np.random.rand(4,5).reshape(10,2)

In [223]:
m1

array([[0.14156042, 0.41210333],
       [0.31311217, 0.52631559],
       [0.22914185, 0.48414811],
       [0.9036989 , 0.72684387],
       [0.67258401, 0.21528355],
       [0.32888668, 0.21469993],
       [0.25083564, 0.7964822 ],
       [0.8882079 , 0.07954522],
       [0.90016398, 0.9204571 ],
       [0.11010193, 0.41172063]])

In [224]:
np.sqrt(m1)

array([[0.37624515, 0.64195275],
       [0.55956427, 0.72547611],
       [0.47868763, 0.69580752],
       [0.95063079, 0.85255139],
       [0.82011219, 0.46398658],
       [0.57348643, 0.46335724],
       [0.50083494, 0.89245851],
       [0.94244782, 0.28203762],
       [0.94876972, 0.95940455],
       [0.33181611, 0.6416546 ]])

In [225]:
np.exp(m1)

array([[1.15207011, 1.50999046],
       [1.36767494, 1.69268426],
       [1.2575204 , 1.62279198],
       [2.46871777, 2.0685417 ],
       [1.95929362, 1.2402135 ],
       [1.3894204 , 1.23948991],
       [1.28509885, 2.21772567],
       [2.43076956, 1.08279452],
       [2.46000646, 2.51043765],
       [1.11639186, 1.50941269]])

In [226]:
np.log10(m1)

array([[-0.84905817, -0.38499387],
       [-0.50430005, -0.27875377],
       [-0.63989559, -0.31502176],
       [-0.04397625, -0.13855887],
       [-0.17225346, -0.66698916],
       [-0.48295371, -0.66816809],
       [-0.60061075, -0.09882393],
       [-0.05148537, -1.09938593],
       [-0.04567837, -0.03599645],
       [-0.95820507, -0.38539737]])

In [227]:
m1 

array([[0.14156042, 0.41210333],
       [0.31311217, 0.52631559],
       [0.22914185, 0.48414811],
       [0.9036989 , 0.72684387],
       [0.67258401, 0.21528355],
       [0.32888668, 0.21469993],
       [0.25083564, 0.7964822 ],
       [0.8882079 , 0.07954522],
       [0.90016398, 0.9204571 ],
       [0.11010193, 0.41172063]])

In [228]:
m

array([[0.14455958, 0.20938182],
       [0.83605175, 0.55520719],
       [0.43425885, 0.48619   ],
       [0.39130041, 0.49192625],
       [0.76129507, 0.49570495],
       [0.46454378, 0.68464389],
       [0.60547977, 0.86975051],
       [0.58402069, 0.52695175],
       [0.51751644, 0.21480888],
       [0.78930128, 0.80285651]])

In [230]:
np.fmod(m,m1)

array([[0.00299917, 0.20938182],
       [0.20982741, 0.0288916 ],
       [0.205117  , 0.0020419 ],
       [0.39130041, 0.49192625],
       [0.08871106, 0.06513786],
       [0.1356571 , 0.0405441 ],
       [0.10380849, 0.07326831],
       [0.58402069, 0.04968044],
       [0.51751644, 0.21480888],
       [0.01858778, 0.39113588]])

In [235]:
n = np.array([[3,4,5],[1,2,3],[3,6,7]],ndmin = 10 )

In [236]:
n

array([[[[[[[[[[3, 4, 5],
               [1, 2, 3],
               [3, 6, 7]]]]]]]]]])

In [237]:
n.shape

(1, 1, 1, 1, 1, 1, 1, 1, 3, 3)

In [238]:
n1 = np.array([[3,4,5],[1,2,3],[3,6,7]])

In [244]:
n1.reshape(3,1,3)

array([[[3, 4, 5]],

       [[1, 2, 3]],

       [[3, 6, 7]]])

In [240]:
n1.shape

(3, 3)

In [241]:
n1.ndim

2